name: Release Flow
on:
  push:
    branches: 
      - master

concurrency:
  group: release-master
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - run: git add -f src binding.gyp
      - run: git commit -m'yet another release'
      - name: Push to the release branch
        run: git push origin master:release
